apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: bigg
  name:	bigg-harmonizer
spec:
  replicas: 10
  selector:
    matchLabels:
      app: bigg-harmonizer
  strategy:
    type: Recreate
  template:
    metadata:
        labels:
            app: bigg-harmonizer
    spec:
      hostAliases:
        - ip: "10.0.88.76"
          hostnames:
            - "master1.internal"
        - ip: "10.0.87.95"
          hostnames:
            - "master2.internal"
        - ip: "10.0.88.132"
          hostnames:
            - "worker1.internal"
        - ip: "10.0.86.33"
          hostnames:
            - "worker2.internal"
        - ip: "10.0.87.145"
          hostnames:
            - "worker3.internal"
        - ip: "10.0.86.214"
          hostnames:
            - "worker4.internal"
        - ip: "10.0.129.220"
          hostnames:
            - "kafka1.internal"
      containers:
        - name: bigg-harmonizer
          image: docker.tech.beegroup-cimne.com/jobs/importing_tool:latest
          command: ["python3", "-m", "harmonizer"]
          volumeMounts:
          - name: biggsecrets
            mountPath: /home/ubuntu/beegroup_importing_tool/config.json
            subPath: config.json

          - name: biggsecrets
            mountPath: /home/ubuntu/beegroup_importing_tool/sources/Datadis/config.json
            subPath: config_datadis.json

          - name: biggsecrets
            mountPath: /home/ubuntu/beegroup_importing_tool/sources/Gemweb/config.json
            subPath: config_gemweb.json

          - name: biggsecrets
            mountPath: /home/ubuntu/beegroup_importing_tool/sources/Genercat/config.json
            subPath: config_genercat.json

          - name: biggsecrets
            mountPath: /home/ubuntu/beegroup_importing_tool/sources/GPG/config.json
            subPath: config_gpg.json

          - name: biggsecrets
            mountPath: /home/ubuntu/beegroup_importing_tool/sources/Weather/config.json
            subPath: config_weather.json

          - name: biggsecrets
            mountPath: /home/ubuntu/beegroup_importing_tool/sources/Nedgia/config.json
            subPath: config_nedgia.json

          - name: biggsecrets
            mountPath: /home/ubuntu/beegroup_importing_tool/.env
            subPath: .env


      imagePullSecrets:
        - name: registrypullsecret
            
      volumes:
        - name: biggsecrets
          secret:
            secretName: main
            items:
            - key: config.json
              path: config.json
            - key: config_datadis.json
              path: config_datadis.json
            - key: config_gemweb.json
              path: config_gemweb.json
            - key: config_genercat.json
              path: config_genercat.json
            - key: config_gpg.json
              path: config_gpg.json
            - key: config_weather.json
              path: config_weather.json
            - key: config_nedgia.json
              path: config_nedgia.json
            - key: .env
              path: .env