import numpy as np
import pandas as pd
from rdflib import Namespace

from sources.GMAO.harmonizer.mapper import Mapper
from utils.data_transformations import decode_hbase, building_space_subject
from utils.rdf_utils.rdf_functions import generate_rdf
from utils.rdf_utils.save_rdf import save_rdf_with_source


def split_zone_name(value):
    spl = value.split('.')
    building_type = spl[0]
    building = spl[1]
    space = building if spl[2] == '' else '.'.join(spl[1:])
    parent_space = '.'.join(spl[1:-1])
    return f"{building_type},{building},{space},{parent_space}"


def harmonize_full_zone(data, **kwargs):
    df = pd.DataFrame(data)
    df = df.applymap(decode_hbase)
    df.drop(['typology', 'criticalities', 'managedscopes', 'operations', 'featuresvalues'], axis=1, inplace=True)
    df[['building_type', 'building_id', 'building_space', 'building_space_parent']] = df['zonepath'].apply(
        split_zone_name).str.split(',', expand=True)

    df['buildingSpace_subject'] = df['building_space'].apply(building_space_subject)
    df['hasSubSpace'] = df.apply(
        lambda x: building_space_subject(x['building_space_parent']) if x['building_space'] != x[
            'building_id'] else np.NaN, axis=1)

    # TODO: hasBuildingSpaceUseType

    save_df(df, 'zone', **kwargs)
    data = [{'id': 'be5a976d-f260-4789-a5e2-0e6c6e00e2d9', 'parentid': 'e0b42485-0f81-4356-a796-d8193d5c4453',
             'zonepath': 'BEN.BSV-06359.', 'name': 'Residència Roger de Llúria',
             'typology': {'id': '67a7cc22-b1e2-4004-b389-36a9883e2bd9', 'name': 'Edifici 1', 'isselectable': False},
             'criticalities': [], 'managedscopes': [
            {'service': 'Maintenance', 'id': 'f74d92da-41fe-42a0-8a0b-e60a69905621', 'name': 'Nou Lot 12',
             'isselectable': False}], 'operations': [{'id': '8ae6fe13-2055-416b-8299-354ee4636c20',
                                                      'classification': {'service': 'Maintenance',
                                                                         'id': '45e50d93-4138-40d5-9be9-2be3ad343566',
                                                                         'name': '01 BAIXA TENSIÓ Instal·lació general (Pública concurrència)',
                                                                         'isselectable': False},
                                                      'periodicity': {'id': '9455e5ff-eaa0-4fd3-a1b7-ff05d2f13e6f',
                                                                      'name': 'Anual', 'isselectable': False},
                                                      'level': {'id': '3fe4295b-ddfb-431c-abe2-18fafe361b4b',
                                                                'name': '10_NS7', 'isselectable': False},
                                                      'description': '01 BAIXA TENSIÓ Instal·lació general (Pública concurrència)'},
                                                     {'id': '6ad54854-0435-4626-af52-fe0c1510d885',
                                                      'classification': {'service': 'Maintenance',
                                                                         'id': 'e6120e33-69db-4aaf-be17-d31807a76a14',
                                                                         'name': '03 BAIXA TENSIÓ Parallamps',
                                                                         'isselectable': False},
                                                      'periodicity': {'id': '9455e5ff-eaa0-4fd3-a1b7-ff05d2f13e6f',
                                                                      'name': 'Anual', 'isselectable': False},
                                                      'level': {'id': '512f974a-db0c-4b17-a19d-a000ba55fe42',
                                                                'name': '2_NS7', 'isselectable': False},
                                                      'description': '03 BAIXA TENSIÓ Parallamps'},
                                                     {'id': 'eb27ada7-c66b-4da5-91c1-d1263985f35e',
                                                      'classification': {'service': 'Maintenance',
                                                                         'id': '257e83c3-7399-454b-b541-137dc92dc81c',
                                                                         'name': '04 BAIXA TENSIÓ Revisió i manteniment del grup electrògen i la seva conmutació',
                                                                         'isselectable': False},
                                                      'periodicity': {'id': '9455e5ff-eaa0-4fd3-a1b7-ff05d2f13e6f',
                                                                      'name': 'Anual', 'isselectable': False},
                                                      'level': {'id': '3fe4295b-ddfb-431c-abe2-18fafe361b4b',
                                                                'name': '10_NS7', 'isselectable': False},
                                                      'description': '04 BAIXA TENSIÓ Revisió i manteniment del grup electrògen i la seva conmutació'},
                                                     {'id': 'd32e2229-30bd-4af7-9384-c60212b1a59e',
                                                      'classification': {'service': 'Maintenance',
                                                                         'id': 'c92a9fb9-1df7-4cc6-ae3a-2a382426e6c8',
                                                                         'name': '07 INSTAL·LACIÓ GAS ERM i punts de consum',
                                                                         'isselectable': False},
                                                      'periodicity': {'id': '9455e5ff-eaa0-4fd3-a1b7-ff05d2f13e6f',
                                                                      'name': 'Anual', 'isselectable': False},
                                                      'level': {'id': '87aa5f64-b5ba-4bad-ad29-cd35eaa4a78c',
                                                                'name': '5_NS7', 'isselectable': False},
                                                      'description': '07 INSTAL·LACIÓ GAS ERM i punts de consum'},
                                                     {'id': '2d9c9560-500f-41a2-862f-3084f32c8723',
                                                      'classification': {'service': 'Maintenance',
                                                                         'id': '5d3ccdfe-fbe4-48e9-8a1d-3bb761ca1247',
                                                                         'name': '10 INSTAL·LACIONS CLIMATITZACIO Generadors de calor de potència tèrmica 20 KW < P <1000 KW',
                                                                         'isselectable': False},
                                                      'periodicity': {'id': '9455e5ff-eaa0-4fd3-a1b7-ff05d2f13e6f',
                                                                      'name': 'Anual', 'isselectable': False},
                                                      'level': {'id': '3fe4295b-ddfb-431c-abe2-18fafe361b4b',
                                                                'name': '10_NS7', 'isselectable': False},
                                                      'description': '10 INSTAL·LACIONS CLIMATITZACIO Generadors de calor de potència tèrmica 20 KW < P <1000 KW'},
                                                     {'id': 'a40778e6-0809-418e-bad7-304c46676f12',
                                                      'classification': {'service': 'Maintenance',
                                                                         'id': '1e3246fc-0a5f-4cb2-804a-d8ac90cb4ec0',
                                                                         'name': '11 INSTAL·LACIONS CLIMATITZACIO A Generadors de fred de potència 12 KW < P <1000 KW',
                                                                         'isselectable': False},
                                                      'periodicity': {'id': '9455e5ff-eaa0-4fd3-a1b7-ff05d2f13e6f',
                                                                      'name': 'Anual', 'isselectable': False},
                                                      'level': {'id': '8d7dac5e-15f3-46f3-82d7-bd1ac35e6e17',
                                                                'name': '15_NS7', 'isselectable': False},
                                                      'description': '11 INSTAL·LACIONS CLIMATITZACIO A Generadors de fred de potència 12 KW < P <1000 KW'},
                                                     {'id': '00e91772-2290-4769-9348-42610bc2c43d',
                                                      'classification': {'service': 'Maintenance',
                                                                         'id': '2482a04c-3e4d-43e8-a10b-d34f67fa2872',
                                                                         'name': '12.14 LEGIONEL·LA (NETEJA & DESINFECCIO)',
                                                                         'isselectable': False},
                                                      'periodicity': {'id': '9455e5ff-eaa0-4fd3-a1b7-ff05d2f13e6f',
                                                                      'name': 'Anual', 'isselectable': False},
                                                      'level': {'id': '3fe4295b-ddfb-431c-abe2-18fafe361b4b',
                                                                'name': '10_NS7', 'isselectable': False},
                                                      'description': '12.14 LEGIONEL·LA (NETEJA & DESINFECCIO)'},
                                                     {'id': 'af83fe5a-0035-4fae-a77b-1e05dcd4c174',
                                                      'classification': {'service': 'Maintenance',
                                                                         'id': 'c92f6287-36c8-4689-9446-c8e429234af9',
                                                                         'name': '12.18 Legionel·la ACS i AFCH Analítiques - Residencia de Roger de Lluria',
                                                                         'isselectable': False},
                                                      'periodicity': {'id': '7aeedfcd-0461-416a-8192-641b511115d7',
                                                                      'name': 'Semestral', 'isselectable': False},
                                                      'level': {'id': '3fe4295b-ddfb-431c-abe2-18fafe361b4b',
                                                                'name': '10_NS7', 'isselectable': False},
                                                      'description': '12.18 Legionel·la ACS i AFCH Analítiques - Residencia de Roger de Lluria'},
                                                     {'id': '0678b2bd-4855-42a0-aa83-ef3d4ccecf60',
                                                      'classification': {'service': 'Maintenance',
                                                                         'id': 'a5b47289-3470-446c-9028-64a13f343dc1',
                                                                         'name': '13 SISTEMA DE CONTRA INCENDIS Revisió anual del sistema de detecció contra incendis',
                                                                         'isselectable': False},
                                                      'periodicity': {'id': '9455e5ff-eaa0-4fd3-a1b7-ff05d2f13e6f',
                                                                      'name': 'Anual', 'isselectable': False},
                                                      'level': {'id': '87aa5f64-b5ba-4bad-ad29-cd35eaa4a78c',
                                                                'name': '5_NS7', 'isselectable': False},
                                                      'description': '13 SISTEMA DE CONTRA INCENDIS Revisió anual del sistema de detecció contra incendis'},
                                                     {'id': 'e5edc437-c62d-4cb4-82fe-4cff4efc4218',
                                                      'classification': {'service': 'Maintenance',
                                                                         'id': 'b71e7ca3-0133-49cd-8022-0636037f06ca',
                                                                         'name': "14 SISTEMA DE CONTRA INCENDIS Revisió anual d'extintors, hidrants i BIES",
                                                                         'isselectable': False},
                                                      'periodicity': {'id': '9455e5ff-eaa0-4fd3-a1b7-ff05d2f13e6f',
                                                                      'name': 'Anual', 'isselectable': False},
                                                      'level': {'id': '3fe4295b-ddfb-431c-abe2-18fafe361b4b',
                                                                'name': '10_NS7', 'isselectable': False},
                                                      'description': "14 SISTEMA DE CONTRA INCENDIS Revisió anual d'extintors, hidrants i BIES"},
                                                     {'id': 'd695a333-ee97-4556-9c56-8f91303f5367',
                                                      'classification': {'service': 'Maintenance',
                                                                         'id': 'df662f54-8187-489a-ba6c-d61801b34ed1',
                                                                         'name': "16 REVISIO DE SISTEMAS DE PROTECCIO COL·LECTIVA Revisió anual de linies de vida i punts d'ancoratge",
                                                                         'isselectable': False},
                                                      'periodicity': {'id': '9455e5ff-eaa0-4fd3-a1b7-ff05d2f13e6f',
                                                                      'name': 'Anual', 'isselectable': False},
                                                      'level': {'id': '8d7dac5e-15f3-46f3-82d7-bd1ac35e6e17',
                                                                'name': '15_NS7', 'isselectable': False},
                                                      'description': "16 REVISIO DE SISTEMAS DE PROTECCIO COL·LECTIVA Revisió anual de linies de vida i punts d'ancoratge"},
                                                     {'id': '6ea9869d-1e25-4a9b-9a7a-8484672bd501',
                                                      'classification': {'service': 'Maintenance',
                                                                         'id': '0ac62862-6853-497a-87f1-4b4e91cfe823',
                                                                         'name': '18.10 Control SAT - Control',
                                                                         'isselectable': False},
                                                      'periodicity': {'id': '7aeedfcd-0461-416a-8192-641b511115d7',
                                                                      'name': 'Semestral', 'isselectable': False},
                                                      'level': {'id': '3fe4295b-ddfb-431c-abe2-18fafe361b4b',
                                                                'name': '10_NS7', 'isselectable': False},
                                                      'description': '18.10 Control SAT - Control'},
                                                     {'id': 'bd555913-6fc7-4a5a-9853-f2a4dd45bcf8',
                                                      'classification': {'service': 'Maintenance',
                                                                         'id': '341da6d3-cba2-460b-944f-607a09c6bbba',
                                                                         'name': '19 EIC APARELLS ELEVADORS Ascensors en edificis industrials i de pública concurrència',
                                                                         'isselectable': False},
                                                      'periodicity': {'id': '896547f7-65a2-421b-931c-740cdd710daf',
                                                                      'name': 'Bienal', 'isselectable': False},
                                                      'level': {'id': '3fe4295b-ddfb-431c-abe2-18fafe361b4b',
                                                                'name': '10_NS7', 'isselectable': False},
                                                      'description': '19 EIC APARELLS ELEVADORS Ascensors en edificis industrials i de pública concurrència'},
                                                     {'id': 'f0b78e27-6c2c-41ac-9ee1-9e6b59df0c7e',
                                                      'classification': {'service': 'Maintenance',
                                                                         'id': 'adb7fec1-59a3-4143-9200-8c349901fba2',
                                                                         'name': '19.1 EIC APARELLS ELEVADORS Ascensors en edificis industrials i de pública concurrència',
                                                                         'isselectable': False},
                                                      'periodicity': {'id': '896547f7-65a2-421b-931c-740cdd710daf',
                                                                      'name': 'Bienal', 'isselectable': False},
                                                      'level': {'id': '3fe4295b-ddfb-431c-abe2-18fafe361b4b',
                                                                'name': '10_NS7', 'isselectable': False},
                                                      'description': '19.1 EIC APARELLS ELEVADORS Ascensors en edificis industrials i de pública concurrència'},
                                                     {'id': 'aa350196-622a-41d7-a63d-9753eddc88ed',
                                                      'classification': {'service': 'Maintenance',
                                                                         'id': 'f5fd712e-80b1-4b92-8467-67103ceeeac1',
                                                                         'name': '22 EIC INSTAL·LACIONS CLIMATITZACIO Generadors de calor de potència tèrmica 20 KW < P <1000 KW',
                                                                         'isselectable': False},
                                                      'periodicity': {'id': '8401ae3a-2757-4da8-ba62-53ebaff39973',
                                                                      'name': 'Quadriennal', 'isselectable': False},
                                                      'level': {'id': 'fb039f22-5efc-4045-a282-607fdb4dac04',
                                                                'name': '8_NS7', 'isselectable': False},
                                                      'description': '22 EIC INSTAL·LACIONS CLIMATITZACIO Generadors de calor de potència tèrmica 20 KW < P <1000 KW'},
                                                     {'id': 'd01e2dc8-1e1a-40dc-b5f1-6d270f8f1ab2',
                                                      'classification': {'service': 'Maintenance',
                                                                         'id': 'f7ca64dd-c742-48d7-8826-525b9f861cfe',
                                                                         'name': '23.1 EIC INSTAL·LACIONS CLIMATITZACIO A Generadors de fred de potència 12 KW < P <1000 KW',
                                                                         'isselectable': False},
                                                      'periodicity': {'id': '2a843965-3071-4c77-b6d0-68cbdd34dbfa',
                                                                      'name': 'Quinquennal', 'isselectable': False},
                                                      'level': {'id': '3fe4295b-ddfb-431c-abe2-18fafe361b4b',
                                                                'name': '10_NS7', 'isselectable': False},
                                                      'description': '23.1 EIC INSTAL·LACIONS CLIMATITZACIO A Generadors de fred de potència 12 KW < P <1000 KW'},
                                                     {'id': 'c64f015c-5515-4ba0-b118-52eb87b2b497',
                                                      'classification': {'service': 'Maintenance',
                                                                         'id': '2a6fa3b1-7e76-4fd4-9b44-e807e4af434b',
                                                                         'name': '24 EIC LEGIONELA Neteja, desinfecció, analítiques i revisió llibre de prevenció de Legionel·losis',
                                                                         'isselectable': False},
                                                      'periodicity': {'id': '8401ae3a-2757-4da8-ba62-53ebaff39973',
                                                                      'name': 'Quadriennal', 'isselectable': False},
                                                      'level': {'id': '3fe4295b-ddfb-431c-abe2-18fafe361b4b',
                                                                'name': '10_NS7', 'isselectable': False},
                                                      'description': '24 EIC LEGIONELA Neteja, desinfecció, analítiques i revisió llibre de prevenció de Legionel·losis'},
                                                     {'id': '60866093-a8ea-49b8-8d35-0f85146a582d',
                                                      'classification': {'service': 'Maintenance',
                                                                         'id': '2ee05997-f538-418c-9053-9c05600d13e2',
                                                                         'name': '25 EIC BAIXA TENSIÓ Instal·lació general (Pública concurrència)',
                                                                         'isselectable': False},
                                                      'periodicity': {'id': '2a843965-3071-4c77-b6d0-68cbdd34dbfa',
                                                                      'name': 'Quinquennal', 'isselectable': False},
                                                      'level': {'id': '3fe4295b-ddfb-431c-abe2-18fafe361b4b',
                                                                'name': '10_NS7', 'isselectable': False},
                                                      'description': '25 EIC BAIXA TENSIÓ Instal·lació general (Pública concurrència)'},
                                                     {'id': '852e9637-5245-4746-b7f9-77625fdd17be',
                                                      'classification': {'service': 'Maintenance',
                                                                         'id': '2e34df12-3f69-40c8-a680-2664e74d4bfe',
                                                                         'name': '29.1 SISTEMA DE CONTRA INCENDIS Retimbrat extintors',
                                                                         'isselectable': False},
                                                      'periodicity': {'id': '9455e5ff-eaa0-4fd3-a1b7-ff05d2f13e6f',
                                                                      'name': 'Anual', 'isselectable': False},
                                                      'level': {'id': '87aa5f64-b5ba-4bad-ad29-cd35eaa4a78c',
                                                                'name': '5_NS7', 'isselectable': False},
                                                      'description': '29.1 SISTEMA DE CONTRA INCENDIS Retimbrat extintors'},
                                                     {'id': 'dcaa36b7-f25d-452b-aa50-3c605497b353',
                                                      'classification': {'service': 'Maintenance',
                                                                         'id': '076329e4-e8d5-4f06-b7f1-d11497e94bcb',
                                                                         'name': '30.2 SISTEMA DE CONTRA INCENDIS Retimbrat BIES',
                                                                         'isselectable': False},
                                                      'periodicity': {'id': '9455e5ff-eaa0-4fd3-a1b7-ff05d2f13e6f',
                                                                      'name': 'Anual', 'isselectable': False},
                                                      'level': {'id': '87aa5f64-b5ba-4bad-ad29-cd35eaa4a78c',
                                                                'name': '5_NS7', 'isselectable': False},
                                                      'description': '30.2 SISTEMA DE CONTRA INCENDIS Retimbrat BIES'},
                                                     {'id': '0322d988-5c43-45ea-b86e-bdb28b6a697b',
                                                      'classification': {'service': 'Maintenance',
                                                                         'id': '16362fd3-598c-4583-b766-731262295b2d',
                                                                         'name': '32 EIC INSTAL·LACIÓ GAS ERM i punts de consum',
                                                                         'isselectable': False},
                                                      'periodicity': {'id': '2a843965-3071-4c77-b6d0-68cbdd34dbfa',
                                                                      'name': 'Quinquennal', 'isselectable': False},
                                                      'level': {'id': '87aa5f64-b5ba-4bad-ad29-cd35eaa4a78c',
                                                                'name': '5_NS7', 'isselectable': False},
                                                      'description': '32 EIC INSTAL·LACIÓ GAS ERM i punts de consum'},
                                                     {'id': '8b6f17ab-ffa9-4ddf-b452-5dda012efe0b',
                                                      'classification': {'service': 'Maintenance',
                                                                         'id': 'e7837f64-f19c-4172-a9a2-a614b14ccba4',
                                                                         'name': '39 EIC RIPCI', 'isselectable': False},
                                                      'periodicity': {'id': '76a9c8ad-8be3-4e81-b11d-907d72c75996',
                                                                      'name': 'Decennal', 'isselectable': False},
                                                      'level': {'id': 'ce07b0ec-3b71-4c17-a913-3ce683beb27b',
                                                                'name': '20_NS7', 'isselectable': False},
                                                      'description': '39 EIC RIPCI'},
                                                     {'id': 'dc053ce4-697b-4053-bbcc-767ac5584bd4',
                                                      'classification': {'service': 'Maintenance',
                                                                         'id': '1e0f5b45-bdc6-48e0-baa7-ae0f7695af55',
                                                                         'name': 'VENTILACIÓ EN CENTRES DE TREBALL - IDA 2 - QUINZENAL',
                                                                         'isselectable': False},
                                                      'periodicity': {'id': 'ad2984c0-6b9a-4423-9b79-9b41a255347c',
                                                                      'name': 'Quinzenal', 'isselectable': False},
                                                      'level': {'id': '05308ac9-ac53-40ba-8ed9-ebd5cde5a96a',
                                                                'name': 'Ordinari', 'isselectable': False},
                                                      'description': 'Comprovacions quinzenals en la ventilació - IDA 2'}],
             'featuresvalues': [{'featureid': '55ad749d-bf5f-4303-b151-15576de5dac5', 'featurename': 'Import',
                                 'featuregroup': 'Dades contractuals', 'featurecaption': 'Import',
                                 'featurevalue': '224489.46'},
                                {'featureid': 'f68d4c37-9cdc-4500-9f86-3c51860d3b68', 'featurename': 'NVisitesSetmana',
                                 'featuregroup': 'Dades contractuals', 'featurecaption': 'Nº visites setmana',
                                 'featurevalue': '5'},
                                {'featureid': '52151a24-2406-4f83-adab-969feb799a4d', 'featurename': 'VAR',
                                 'featuregroup': 'Dades contractuals', 'featurecaption': 'VAR', 'featurevalue': '5'},
                                {'featureid': 'df858a55-e994-47cd-ac42-ce41fdb1c88c', 'featurename': 'Referencia',
                                 'featuregroup': 'Dades contractuals', 'featurecaption': 'Referència',
                                 'featurevalue': '49'},
                                {'featureid': '76e942fc-8462-432a-b366-313f84660681', 'featurename': 'Lot',
                                 'featuregroup': 'Dades contractuals', 'featurecaption': 'Lot',
                                 'featurevalue': 'Lot 12'},
                                {'featureid': 'e87f67ad-d5a1-40e2-acc1-78ea373a7fd0', 'featurename': 'K1',
                                 'featuregroup': 'Dades contractuals', 'featurecaption': 'K1', 'featurevalue': '0.945'},
                                {'featureid': 'b0e5e6e0-770b-4287-bc8e-bbe2cf29fffa', 'featurename': 'Import2225',
                                 'featuregroup': 'Dades contractuals', 'featurecaption': 'Import 22-25',
                                 'featurevalue': '401317.97'}, {'featureid': 'c7d41c9a-07f8-4377-95f8-8a7831e766e8',
                                                                'featurename': 'G21BDataLimitPosadaAPuntDelSIE',
                                                                'featuregroup': 'Servei eficiència energètica 21-24',
                                                                'featurecaption': 'G21B-1B - Data límit Posada a punt del SIE (Inicial)',
                                                                'featurevalue': '2022-06-01T00:00:00'},
                                {'featureid': '4aeb8e96-b615-488b-b346-6ac3ddc2adda',
                                 'featurename': 'G22BDataLimitPosadaAPuntDelTelecontrol',
                                 'featuregroup': 'Servei eficiència energètica 21-24',
                                 'featurecaption': 'G22B-1B - Data límit Posada a punt del Telecontrol (inicial)',
                                 'featurevalue': '2022-06-01T00:00:00'},
                                {'featureid': '4e57f9ba-418d-4fc5-a816-a23acc789a5e',
                                 'featurename': 'G23BDataLimitAprovacioLInformeDIncidenc i',
                                 'featuregroup': 'Servei eficiència energètica 21-24',
                                 'featurecaption': "G23B-1B - Data límit Aprovació l’informe d'incidències del SIE-Telecontrol (inicial)",
                                 'featurevalue': '2022-06-01T00:00:00'},
                                {'featureid': 'f84da4fb-9b71-4176-b862-b086e2611c25',
                                 'featurename': 'G24BDataLimitLliuramentDelsPlansDUsos',
                                 'featuregroup': 'Servei eficiència energètica 21-24',
                                 'featurecaption': "G24B-1B - Data límit Lliurament dels Plans d'usos (inicial)",
                                 'featurevalue': '2022-07-01T00:00:00'},
                                {'featureid': '5df39d33-b65c-4aaa-8489-bac827c91e7a',
                                 'featurename': 'G25BDataLimitAprovacioBaseLines',
                                 'featuregroup': 'Servei eficiència energètica 21-24',
                                 'featurecaption': 'G25B-1B - Data límit Aprovació “Base lines”(inicial)',
                                 'featurevalue': '2022-07-01T00:00:00'},
                                {'featureid': 'd4147db3-b7ec-49d9-9e0a-87d73905fb81',
                                 'featurename': 'G26BDataLimitLliuramentDelCatalegDAME',
                                 'featuregroup': 'Servei eficiència energètica 21-24',
                                 'featurecaption': 'G26B-1B - Data límit Lliurament del catàleg d’AME (inicial)',
                                 'featurevalue': '2022-07-01T00:00:00'},
                                {'featureid': '9ca80415-285c-4073-bc14-8d40e43cda55',
                                 'featurename': 'G27BDataLimitAprovacioDeLesAuditoriesEne',
                                 'featuregroup': 'Servei eficiència energètica 21-24',
                                 'featurecaption': 'G27B-1B - Data límit Aprovació de les auditories energètiques (inicial)',
                                 'featurevalue': '2022-08-01T00:00:00'},
                                {'featureid': '47fccdab-72fb-4b26-88fd-5ed1e18cb30f',
                                 'featurename': 'G28BDataLimitAprovacioDelPlaDAME',
                                 'featuregroup': 'Servei eficiència energètica 21-24',
                                 'featurecaption': "G28B-1B - Data límit Aprovació del Pla d'AME (inicial)",
                                 'featurevalue': '2022-09-01T00:00:00'},
                                {'featureid': '72d297c1-3ca4-4dba-8807-c688d90bff9b',
                                 'featurename': 'G21B2BDataLimitPosadaAPuntDelSIEAny2',
                                 'featuregroup': 'Servei eficiència energètica 21-24',
                                 'featurecaption': 'G21B-2B - Data límit Posada a punt del SIE (any 2)',
                                 'featurevalue': '2023-06-01T00:00:00'},
                                {'featureid': 'd02611d2-b54f-4670-a556-11e716445cc2',
                                 'featurename': 'G21B3BDataLimitPosadaAPuntDelSIEAny3',
                                 'featuregroup': 'Servei eficiència energètica 21-24',
                                 'featurecaption': 'G21B-3B - Data límit Posada a punt del SIE (any 3)',
                                 'featurevalue': '2024-06-01T00:00:00'},
                                {'featureid': 'cb262fec-76b3-41dc-8995-d90b2efcf0da',
                                 'featurename': 'G25B2BDataLimitAprovacioBaseLinesAny2',
                                 'featuregroup': 'Servei eficiència energètica 21-24',
                                 'featurecaption': 'G25B-2B - Data límit Aprovació “Base lines”(any 2)',
                                 'featurevalue': '2023-07-01T00:00:00'},
                                {'featureid': 'df5162ae-d0d7-426f-aa6e-891067b66cf1',
                                 'featurename': 'G25B3BDataLimitAprovacioBaseLinesAny3',
                                 'featuregroup': 'Servei eficiència energètica 21-24',
                                 'featurecaption': 'G25B-3B - Data límit Aprovació “Base lines”(any 3)',
                                 'featurevalue': '2024-07-01T00:00:00'},
                                {'featureid': '2e56875f-d95f-4288-be15-51e69a7bc280',
                                 'featurename': 'G26B2BDataLimitLliuramentDelCatalegDAMEA',
                                 'featuregroup': 'Servei eficiència energètica 21-24',
                                 'featurecaption': 'G26B-2B - Data límit Lliurament del catàleg d’AME (any 2)',
                                 'featurevalue': '2023-07-01T00:00:00'},
                                {'featureid': 'a620eab4-98ed-4a46-964e-5df1d8735458',
                                 'featurename': 'G26B3BDataLimitLliuramentDelCatalegDAMEA',
                                 'featuregroup': 'Servei eficiència energètica 21-24',
                                 'featurecaption': 'G26B-3B - Data límit Lliurament del catàleg d’AME (any 3)',
                                 'featurevalue': '2024-07-01T00:00:00'},
                                {'featureid': '03b3a17c-8c97-4331-9046-7c74b81218f0',
                                 'featurename': 'G21APosadaAPuntDelSIE',
                                 'featuregroup': 'Servei eficiència energètica 21-24',
                                 'featurecaption': 'G21A-1B- Posada a punt del SIE (Inicial)', 'featurevalue': None},
                                {'featureid': 'c2058c5e-91a0-487e-8308-faaeee29f6d1',
                                 'featurename': 'G22APosadaAPuntDelTelecontrol',
                                 'featuregroup': 'Servei eficiència energètica 21-24',
                                 'featurecaption': 'G22A-1B - Posada a punt del Telecontrol (inicial)',
                                 'featurevalue': None}, {'featureid': '13f4e4a4-b268-4697-9116-78668ac69185',
                                                         'featurename': 'G23AAprovacioLInformeDIncidenciesDelSIET',
                                                         'featuregroup': 'Servei eficiència energètica 21-24',
                                                         'featurecaption': "G23A-1B - Aprovació l’informe d'incidències del SIE-Telecontrol (inicial)",
                                                         'featurevalue': None},
                                {'featureid': 'b1ae8f6b-2645-4b9a-9c44-866740142fc5',
                                 'featurename': 'G24ALliuramentDelsPlansDUsos',
                                 'featuregroup': 'Servei eficiència energètica 21-24',
                                 'featurecaption': "G24A -1B- Lliurament dels Plans d'usos (inicial)",
                                 'featurevalue': None}, {'featureid': '8db6bcb6-a856-47d6-83a8-e75203e97c75',
                                                         'featurename': 'G25AAprovacioBaseLines',
                                                         'featuregroup': 'Servei eficiència energètica 21-24',
                                                         'featurecaption': 'G25A-1B - Aprovació “Base lines” (inicial)',
                                                         'featurevalue': None},
                                {'featureid': '9c16e030-5a2f-4b68-ba42-34c816dd4fd6',
                                 'featurename': 'G26ALliuramentDelCatalegDAME',
                                 'featuregroup': 'Servei eficiència energètica 21-24',
                                 'featurecaption': 'G26A-1B - Lliurament del catàleg d’AME (inicial)',
                                 'featurevalue': None}, {'featureid': '3c349076-3f7a-4895-b74c-86c521145e5d',
                                                         'featurename': 'G27AAprovacioDeLesAuditoriesEnergetiques',
                                                         'featuregroup': 'Servei eficiència energètica 21-24',
                                                         'featurecaption': 'G27A-1B - Aprovació de les auditories energètiques (inicial)',
                                                         'featurevalue': None},
                                {'featureid': 'c4c22c0f-ee07-4981-919e-ead574f9659d',
                                 'featurename': 'G28AAprovacioDelPlaDAME',
                                 'featuregroup': 'Servei eficiència energètica 21-24',
                                 'featurecaption': "G28A-1B - Aprovació del Pla d'AME (inicial)", 'featurevalue': None},
                                {'featureid': 'e78da53f-ccf4-47f1-8814-65e4f387bc6c',
                                 'featurename': 'G21A2BPosadaAPuntDelSIEAny2',
                                 'featuregroup': 'Servei eficiència energètica 21-24',
                                 'featurecaption': 'G21A-2B- Posada a punt del SIE (any 2)', 'featurevalue': None},
                                {'featureid': 'a509ada1-f1b2-49c1-8a01-b3844e5f3a15',
                                 'featurename': 'G21A3BPosadaAPuntDelSIEAny3',
                                 'featuregroup': 'Servei eficiència energètica 21-24',
                                 'featurecaption': 'G21A-3B- Posada a punt del SIE (any 3)', 'featurevalue': None},
                                {'featureid': 'edf05a14-2382-4f8c-8ee0-6ffd9683f722',
                                 'featurename': 'G21A4BPosadaAPuntDelSIEADemanda',
                                 'featuregroup': 'Servei eficiència energètica 21-24',
                                 'featurecaption': 'G21A-4B- Posada a punt del SIE (a demanda)', 'featurevalue': None},
                                {'featureid': 'c36cd2fd-78bb-4a1c-ba30-9aa1b2313d32',
                                 'featurename': 'G21B4BDataLimitPosadaAPuntDelSIEADemanda',
                                 'featuregroup': 'Servei eficiència energètica 21-24',
                                 'featurecaption': 'G21B-4B - Data límit Posada a punt del SIE (a demanda)',
                                 'featurevalue': None}, {'featureid': '65b654c2-346c-4ca8-a658-06ae7d16be5d',
                                                         'featurename': 'G22A4BPosadaAPuntDelTelecontrolADemanda',
                                                         'featuregroup': 'Servei eficiència energètica 21-24',
                                                         'featurecaption': 'G22A-4B - Posada a punt del Telecontrol (a demanda)',
                                                         'featurevalue': None},
                                {'featureid': '4209efc7-e24b-4e88-b7f1-4c09b454311c',
                                 'featurename': 'G22B4BDataLimitPosadaAPuntDelTelecontrol',
                                 'featuregroup': 'Servei eficiència energètica 21-24',
                                 'featurecaption': 'G22B-4B - Data límit Posada a punt del Telecontrol (a demanda)',
                                 'featurevalue': None}, {'featureid': '6510670b-8da2-4eb0-a781-5e0a0db1fd55',
                                                         'featurename': 'G23A4BAprovacioLInformeDIncidenciesDelSI',
                                                         'featuregroup': 'Servei eficiència energètica 21-24',
                                                         'featurecaption': "G23A-4B - Aprovació l’informe d'incidències del SIE-Telecontrol (mensual)",
                                                         'featurevalue': None},
                                {'featureid': '1be92aa9-6330-49f9-b016-b1940256fd03',
                                 'featurename': 'G23B4BDataLimitAprovacioLInformeDInciden',
                                 'featuregroup': 'Servei eficiència energètica 21-24',
                                 'featurecaption': "G23B-4B - Data límit Aprovació l’informe d'incidències del SIE-Telecontrol (mensual)",
                                 'featurevalue': None}, {'featureid': '9921e051-c311-4074-980d-121303eaee04',
                                                         'featurename': 'G24A4BLliuramentDelsPlansDUsosADemanda',
                                                         'featuregroup': 'Servei eficiència energètica 21-24',
                                                         'featurecaption': "G24A -4B- Lliurament dels Plans d'usos (a demanda)",
                                                         'featurevalue': None},
                                {'featureid': '3450ff8c-8159-4e6e-acda-75298cd9e7d8',
                                 'featurename': 'G24B4BDataLimitLliuramentDelsPlansDUsosA',
                                 'featuregroup': 'Servei eficiència energètica 21-24',
                                 'featurecaption': "G24B-4B - Data límit Lliurament dels Plans d'usos (a demanda)",
                                 'featurevalue': None}, {'featureid': 'ebab7d3b-d893-47cc-a522-ed351b7e3135',
                                                         'featurename': 'G25A2BAprovacioBaseLinesAny2',
                                                         'featuregroup': 'Servei eficiència energètica 21-24',
                                                         'featurecaption': 'G25A-2B - Aprovació “Base lines” (any 2)',
                                                         'featurevalue': None},
                                {'featureid': 'a0b18648-f8c0-4eb5-9d06-b25ecb902bf1',
                                 'featurename': 'G25A3BAprovacioBaseLinesAny3',
                                 'featuregroup': 'Servei eficiència energètica 21-24',
                                 'featurecaption': 'G25A-3B - Aprovació “Base lines” (any 3)', 'featurevalue': None},
                                {'featureid': 'd0a2a07f-daa7-46d2-a8c3-d50ba2c76b40',
                                 'featurename': 'G25A4BAprovacioBaseLinesADemanda',
                                 'featuregroup': 'Servei eficiència energètica 21-24',
                                 'featurecaption': 'G25A-4B - Aprovació “Base lines” (a demanda)',
                                 'featurevalue': None}, {'featureid': '59c3af6a-c3ec-4640-86d9-b1809672a325',
                                                         'featurename': 'G25B4BDataLimitAprovacioBaseLinesADemand',
                                                         'featuregroup': 'Servei eficiència energètica 21-24',
                                                         'featurecaption': 'G25B-4B - Data límit Aprovació “Base lines”(a demanda)',
                                                         'featurevalue': None},
                                {'featureid': 'c260f535-3a55-44c9-989e-51f1552c8069',
                                 'featurename': 'G26A2BLliuramentDelCatalegDAMEAny2',
                                 'featuregroup': 'Servei eficiència energètica 21-24',
                                 'featurecaption': 'G26A-2B - Lliurament del catàleg d’AME (any 2)',
                                 'featurevalue': None}, {'featureid': '04ad90d1-f007-43a9-8f0b-14a6f72be473',
                                                         'featurename': 'G26A3BLliuramentDelCatalegDAMEAny3',
                                                         'featuregroup': 'Servei eficiència energètica 21-24',
                                                         'featurecaption': 'G26A-3B - Lliurament del catàleg d’AME (any 3)',
                                                         'featurevalue': None},
                                {'featureid': '0eecea5b-352a-468f-b91a-1585c07a0672',
                                 'featurename': 'G28A4BAprovacioDelPlaDAMEADemanda',
                                 'featuregroup': 'Servei eficiència energètica 21-24',
                                 'featurecaption': "G28A-4B - Aprovació del Pla d'AME (a demanda)",
                                 'featurevalue': None}, {'featureid': 'f3898c76-5861-4494-ab5e-14b8efdab5a3',
                                                         'featurename': 'G28B4BDataLimitAprovacioDelPlaDAMEADeman',
                                                         'featuregroup': 'Servei eficiència energètica 21-24',
                                                         'featurecaption': "G28B-4B - Data límit Aprovació del Pla d'AME (a demanda)",
                                                         'featurevalue': None},
                                {'featureid': 'bf309adb-3b9c-4976-94b7-db883fae777e',
                                 'featurename': 'G29A4BInformeDAvaluacioDeLesAMEADemanda',
                                 'featuregroup': 'Servei eficiència energètica 21-24',
                                 'featurecaption': "G29A-4B Informe d'avaluació de les AME (a demanda)",
                                 'featurevalue': None}, {'featureid': '87e052b8-fce3-4b74-92c1-0372a037c6ad',
                                                         'featurename': 'G29B4BDataLimitInformeDAvaluacioDeLesAME',
                                                         'featuregroup': 'Servei eficiència energètica 21-24',
                                                         'featurecaption': "G29B-4B Data límit Informe d'avaluació de les AME (a demanda)",
                                                         'featurevalue': None},
                                {'featureid': 'adbf2a5a-0c3e-4b75-9dc5-a6801115d5f2', 'featurename': 'T',
                                 'featuregroup': 'NS1', 'featurecaption': 'T', 'featurevalue': '264'},
                                {'featureid': 'cf04e430-b2eb-47e8-8800-2af03d5c1452',
                                 'featurename': 'T1LliuramentDeLaPlanificacioAuditoriaEne',
                                 'featuregroup': 'Servei de transició 21-24',
                                 'featurecaption': 'T1 - Lliurament de la planificació auditoria energètica',
                                 'featurevalue': None}, {'featureid': '7e23ded4-48dc-48bf-afbd-715418f1af5f',
                                                         'featurename': 'T2LliuramentDocumentacioAsBuiltSIE',
                                                         'featuregroup': 'Servei de transició 21-24',
                                                         'featurecaption': 'T2 - Lliurament documentació as built SIE',
                                                         'featurevalue': None},
                                {'featureid': '5474c267-f0ae-4a27-99aa-3f0fc023ea5c',
                                 'featurename': 'T3LliuramentAuditoriesInicials',
                                 'featuregroup': 'Servei de transició 21-24',
                                 'featurecaption': 'T3 - Lliurament auditories inicials', 'featurevalue': None},
                                {'featureid': 'ac8f031c-4651-49e3-b3f8-8f11b19f22ff',
                                 'featurename': 'T4CoordinacionsDActivitatEmpresarials',
                                 'featuregroup': 'Servei de transició 21-24',
                                 'featurecaption': 'T4 - Coordinacions d’activitat empresarials',
                                 'featurevalue': None}], 'longitude': 1.089001, 'latitude': 41.158209, 'altitude': None,
             'address': '', 'postalcode': '', 'town': '', 'province': None, 'country': ''}]


def harmonize_assets(data, **kwargs):
    print(data)


def harmonize_full_assets(data, **kwargs): pass


def harmonize_indicator_values(data, **kwargs): pass


def harmonize_work_orders(data, **kwargs): pass


def harmonize_full_work_order(data, **kwargs): pass


def save_df(df, mapping_type, **kwargs):
    namespace = kwargs['namespace']
    config = kwargs['config']
    n = Namespace(namespace)

    mapper = Mapper(config['source'], n)
    g = generate_rdf(mapper.get_mappings(mapping_type), df)

    g.serialize('output.ttl', format="ttl")

    save_rdf_with_source(g, config['source'], config['neo4j'])

    save_rdf_with_source(g, config['source'], config['neo4j'])
